In [2]:
import numpy as np

In [3]:
# arithmetic operations

In [4]:
# methods:

# transpose - row to col & col to row
arr= np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(arr)

print(arr.transpose())
print(arr.T)    # T as shortcut attribute

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
# sorting - row & col wise

arr1= np.array([1,4,3,2,7,5,8,6,4,0])
arr1_sort= np.sort(arr1)
print(arr1)
print(arr1_sort)


[1 4 3 2 7 5 8 6 4 0]
[0 1 2 3 4 4 5 6 7 8]


In [6]:
arr_2d= np.array([[3,44,66],
                  [99,7,3],
                  [29,95,66]])

arr_sort1= np.sort(arr_2d, axis=1)  # axis=1 --> row sort
print(arr_sort1)

[[ 3 44 66]
 [ 3  7 99]
 [29 66 95]]


In [7]:
arr_sort2= np.sort(arr_2d, axis=0)  # axis= 0 --> col sort
print(arr_sort2)

[[ 3  7  3]
 [29 44 66]
 [99 95 66]]


In [8]:
# argsort()- indices of sorted

arr_argsort= np.argsort(arr1)
print("indices of sorted array:", arr_argsort)

indices of sorted array: [9 0 3 2 8 1 5 7 4 6]


In [9]:
# scores= np.random.randfloat(0,10, size=4)

# ranking systems
scores= np.array([0.12, 0.4, 0.2, 0.9, 0.5])
print(scores)

argsort_sc= np.argsort(scores)
print(argsort_sc)

top3= argsort_sc[-3:][::-1]
print(top3)

print(scores[3])

[0.12 0.4  0.2  0.9  0.5 ]
[0 2 1 4 3]
[3 4 1]
0.9


In [10]:
# concatenate

a= np.array([1,2,3])
b= np.array([77,88,99])

res= np.concatenate((a,b))
print(res)


[ 1  2  3 77 88 99]


In [11]:
arr1= np.array([[13,55,67],
                [23,55,77]])
arr2= np.array([[34,56,88],
                [23,60,37]])

res1= np.concatenate((arr1, arr2), axis=1)
res0= np.concatenate((arr1, arr2), axis=0)

print(res1)   # aixs=1 col connect
print(res0)



[[13 55 67 34 56 88]
 [23 55 77 23 60 37]]
[[13 55 67]
 [23 55 77]
 [34 56 88]
 [23 60 37]]


In [12]:
# reshape : change existing arr

arr_1d= np.array([1,2,3,4,5,6,7,8,9])
print(arr_1d)

arr_2d= arr_1d.reshape(3,3)
print(arr_2d)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# conactenate --> numpy [arr focused]
# concat --> pandas

In [14]:
# split() -->

split_arr= np.split(arr_1d, 3)
print(split_arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [15]:
print(arr_2d)
print(arr_2d.reshape(-1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


stats operations:
- np.mean
- np.median
- np.min
- np.max
- np.sum
- np.std --> standard deviation

In [16]:
# stats operations: mean, median, mode, standard deviation,
#  min and max, sum

print(np.mean(arr_2d))

sum_2d= np.sum(arr_2d)
print(sum_2d)

std_dev= np.std(arr_2d)
print(std_dev)

5.0
45
2.581988897471611


In [17]:
# data creation / array creation

arr= np.zeros(9)
print(arr)

arr2= np.zeros((3,4))
print(arr2)

arr3= np.zeros((3,4,3), dtype=int)
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [18]:
a1= np.ones(7, dtype=int)
print(a1)


a2= np.ones((2,3), dtype= str)
print(a2)


[1 1 1 1 1 1 1]
[['1' '1' '1']
 ['1' '1' '1']]


In [19]:
amix= np.full(5,7) # (size, value)
print(amix)

[7 7 7 7 7]


In [23]:
identity_mx= np.eye(4,4)
print(identity_mx)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
# np.arange(start, stop, stepsize)

arr= np.arange(13,35,3)
print(arr)

[13 16 19 22 25 28 31 34]


In [28]:
arr2= np.random.random(6)
print(arr2)

[0.42315563 0.69248392 0.18351375 0.2817596  0.02965944 0.4845014 ]


In [30]:
arr2= np.random.random((3,3))
print(arr2)

[[0.77495013 0.72405789 0.2174663 ]
 [0.51586111 0.56789168 0.07560722]
 [0.3592611  0.60636263 0.71237742]]


In [34]:
# linspace(start,stop,num, endpoint, retstep, dtype)

arr_line= np.linspace(3,6,5, dtype=float)
# divide based on
print(arr_line)

[3.   3.75 4.5  5.25 6.  ]
